[package]
name = "gm-doc"
version = "0.1.0"
edition = "2021"

[dependencies]
roxmltree = "0.18.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
url = { version = "2.4.1", features = ["serde"] }
